version: '3'

services:

    app:
        build: .docker/app
        container_name: app
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            bd:
               condition: service_healthy


    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network

    bd:
        build: .docker/mysql
        command: --innodb-use-native-aio=0
        container_name: bd
        restart: always   
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/bddados:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
        healthcheck:
            test: ["CMD-SHELL",'mysql -u root --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
            interval: 10s
            timeout: 10s
            retries: 10

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
